##
## EPITECH PROJECT, 2024
## minishell2
## File description:
## Makefile
##

NAME		= 42sh

SRCS		= tests_criterion/test_main.c

test:
	ls
	cp ../$(NAME) .
	./tester.sh > ../output.txt
	rm test_redirection_right
	rm test_double_redirection_right
	rm test
	rm $(NAME)
